hotel/app/urls.py
from django.urls import path
from app import views
urlpatterns = [
    path("", views.home, name="HomePage"),
    path("about", views.about_us, name="aboutpage"),
    path("contact", views.contact, name="contact"),
    path("user/bookings", views.user_bookings, name="dashboard"),
    path("user/book-room", views.book_room_page, name="bookroompage"),
    path("user/book-room/book", views.book_room, name="bookroom"),
]

hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('customauth.urls')),
    path("", include('managment.urls')),
    path("", include('app.urls')),
]

hotel/app/models.py
"""
Database Models
"""
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Hotels(models.Model):
    """
    Hotels Info
    Hotel Name, Owner Name, Location, State Country
    """

    hotel_name = models.CharField(max_length=30, default="Naif")
    hotel_owner = models.CharField(max_length=20)
    hotel_location = models.CharField(max_length=50)
    hotel_state = models.CharField(max_length=50, default="Dubai")
    hotel_country = models.CharField(max_length=50, default="UAE")

    def __str__(self):
        return self.hotel_name


class Rooms(models.Model):
    """
    Rooms in the hotel
    Room Type
    Room Availability
    Maximum Capacity
    """

    AVAILABILITY: tuple = (
        ("1", "Available"),
        ("2", "Not Available"),
    )

    ROOM_TYPE: tuple = (
        ("1", "Suite"),
        ("2", "Penthouse"),
        ("3", "Quad Bedroom"),
    )

    room_type = models.CharField(max_length=50, choices=ROOM_TYPE)
    max_capacity = models.IntegerField()
    room_price = models.IntegerField()
    room_size = models.IntegerField()
    hotel = models.ForeignKey(Hotels, on_delete=models.CASCADE)
    availability_status = models.CharField(choices=AVAILABILITY, max_length=15)
    room_number = models.IntegerField()

    def __str__(self):
        return self.hotel.hotel_name


class Reservation(models.Model):
    """
    Reservation of the room
    """

    check_in_date = models.DateField(auto_now=False)
    check_out_date = models.DateField()
    room = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    guest = models.ForeignKey(User, on_delete=models.CASCADE)

    booking_id = models.CharField(max_length=100, default="null")

    def __str__(self):
        return self.guest.username

hotel/templates/user/book_room.html
{% extends 'basic.html' %} {% block title %}Book Room {% endblock title %} {% block body %}
<div class="container">

    <div class="row">
        <div class="col-md-6 col-lg-6 col-xlg-6 col-sm-12 mx-auto my-4 ">

            <form action="/user/book-room/book" method="POST">
                {%csrf_token%}
                {%load app_tags%}
                <div class="form-group">
                    <label for="username">Hotel:</label>
                    <input type="text" class="form-control " id="hotel" name="hotel" disabled value={{room.hotel.hotel_name}}>
                </div>
                <div class="form-group">
                    <label for="username">Location:</label>
                    <input type="text" class="form-control " id="location" name="location" disabled value={{room.hotel.hotel_location}}>
                </div>
                <div class="form-group">
                    <label for="person">username:</label>
                    <input type="text" class="form-control " id="username" name="username" required="true" value={{request.user}}>
                </div>
                <div class="form-group">
                    <label for="person">Person:</label>
                    <input type="number" class="form-control " id="person" name="person" min="1" max={{room.max_capacity}} required="true" value={{room.max_capacity}}>
                </div>
                <div class="form-group">
                    <label for="password2">Check-in:</label>
                    <input type="date" class="form-control " id="cin" min={%todays_date%} max={% max_date %} placeholder="check in " name="check_in" required="True">
                </div>
                <div class="form-group">
                    <label for="password2">Check-Out:</label>
                    <input type="date" class="form-control " id="cout" min={%tommorow%} max={% max_date%} placeholder="check out " name="check_out" required="True">
                </div>
                <div class="form-group">
                    <label for="username">Room Type:</label>
                    <input type="text" class="form-control " id="roomtype" name="roomtype" disabled value={{room.get_room_type_display}}>
                </div>
                <div class="form-group">
                    <label for="password2">Price:</label>
                    <input type="number" class="form-control " id="price" placeholder="price " name="price" disabled value={{room.room_price}}>
                </div>


                <button type="submit" class="btn btn-primary">Book Now</button>
                <input type="hidden" name="room_id" value={{room.id}}>

            </form>
        </div>
    </div>
</div>
{% endblock body %}

hotel/templates/user/my_bookings.html
{% extends 'basic.html' %} {% block title %}Dashboard {% endblock title %} {% block body %}
{% load app_tags %}
<h3 class="text-center  text-success">My Bookings </h3>
<table class="table">
    <thead>
        <th>User</th>
        <th>Room</th>
        <th>Location</th>
        <th>Person</th>
        <th>Check in</th>
        <th>Check out</th>
        <th>Price</th>
    </thead>
    {% for each_booking in bookings %}
    <tr>
        <td>{{each_booking.guest.username}}</td>
        <td>{{each_booking.room.room_number}}</td>
        <td>{{each_booking.room.hotel.hotel_location}}</td>
        <td>{{each_booking.room.max_capacity}}</td>
        <td>{{each_booking.check_in_date}}</td>
        <td>{{each_booking.check_out_date}}</td>
        <td>{{each_booking.room.room_price}}</td>
    </tr>
    {% endfor %}


</table>
{% endblock body %}

hotel/templates/user/user_login_signup.html
{% extends 'basic.html' %}
{% block title %}Login
{% endblock title %}
{% block body %}
<!--Cards starts here-->
<div class="container py-5">


    <!--login and signup tab starts here -->
    <section>
        <div class="card w-50 mx-auto">
            <div class="card-title bg-light ">
                <div class="container mt-3 mx-auto">

                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs justify-content-center w-100 " style="width:358px">

                        <li class="nav-item">
                            <a class="nav-link active " data-toggle="tab" href="#home" style="width:158px">Login</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#menu1" style="width:158px">Signup</a>
                        </li>

                </div>
            </div>


            </ul>
            <div class="card-body">

                <!-- Tab panes -->
                <div class="tab-content">
                    <div id="home" class="container tab-pane active">
                        <p class="text-center text-dark">User login form</p>
                        <div class="container">

                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-xlg-12 col-sm-12">

                                    <form action="/user/login"  method="post">
                                        {%csrf_token%}
                                        <div class="form-group">
                                            <label for="email">Username:</label>
                                            <input type="text" class="form-control " id="email" placeholder="Enter email" name="email">
                                        </div>
                                        <div class="form-group">
                                            <label for="pwd">Password:</label>
                                            <input type="password" class="form-control " id="pwd" placeholder="Enter password" name="pswd">
                                        </div>
                                        <div class="form-group form-check">
                                            <label class="form-check-label">
                                                <input class="form-check-input " type="checkbox" name="remember">
                                                Remember me
                                            </label>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Login</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="menu1" class="container tab-pane fade">
                        <p class="text-center text-dark">User Signup form</p>
                        <div class="container">

                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-xlg-12 col-sm-12">

                                    <form action="/user/signup" method="post">
                                        <div class="form-group">
                                            {%csrf_token%}
                                            <label for="username">Username:</label>
                                            <input type="text" class="form-control " id="username" placeholder="Username" name="username">
                                        </div>

                                        <div class="form-group">
                                            <label for="pwd">Password:</label>
                                            <input type="password" class="form-control " id="password1" placeholder="Enter password" name="password1">
                                        </div>
                                        <div class="form-group">
                                            <label for="pwd">Confirm Password:</label>
                                            <input type="password" class="form-control " id="password2" placeholder="Confirm password" name="password2">
                                        </div>

                                        <button type="submit" class="btn btn-primary">Sign Up</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>



                </div>
            </div>
    </section>
    <!--Login and logout tab ends here-->
    </div>

    <!--Cards ends here-->
{% endblock body %}